# Test model

In [1]:
MODEL_NAME = "models/lstm_word2vec"
TEST_DATASET = "data/test_imdb.csv"

TOKENIZER_NAME = "models/lstm_word2vec_tokenizer"

---

In [3]:
import nltk
import numpy
import pickle
numpy.random.seed(42)

nltk.data.path.insert(0, "/dvl/w3/wn/data/.nltk_data")

from nltk.corpus import stopwords
import pandas as pd
import numpy as np
from itertools import chain
from collections import Counter


from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
from keras.models import model_from_json

Using TensorFlow backend.


Swith on full text mode)

In [4]:
pd.options.display.max_colwidth = -1

## Load data

In [5]:
test_data = pd.read_csv(TEST_DATASET, sep="|")

## Preprocessing

In [6]:
MAX_NB_WORDS = 20000
MAX_SEQUENCE_LENGTH = 70

In [7]:
from nltk.tokenize import TweetTokenizer
tweet_tokenizer = TweetTokenizer()

negatives = {
    "didn't": "didn_`_t",
    "couldn't": "couldn_`_t",
    "don't": "don_`_t",
    "wouldn't": "wouldn_`_t",
    "doesn't": "doesn_`_t",
    "wasn't": "wasn_`_t",
    "weren't": "weren_`_t",
    "shouldn't":"shouldn_`_t",
    "isn't": "isn_`_t",
    "aren't": "aren_`_t",
}

def preprocess(text):
    text = text.lower()
    text = text.replace('<br />', ' ')
    text = ' '.join(tweet_tokenizer.tokenize(text))
    for k, v in negatives.items():
        text = text.replace(k, v)
    return text

In [8]:
test_data['prep_text'] = test_data['text'].map(preprocess)

#### 1. String -> Int vector

In [9]:
 #load tokenizer
pkl_file = open(TOKENIZER_NAME, 'rb')
tokenizer = pickle.load(pkl_file)
pkl_file.close()

#### 2. Padding

In [10]:
sequences_test = tokenizer.texts_to_sequences(test_data['prep_text'])

padded_sequences_test = pad_sequences(sequences_test, maxlen=MAX_SEQUENCE_LENGTH)

In [59]:
padded_sequences_test

array([[   11,     6,    87, ...,    55,    82,    17],
       [10361,   182,   175, ...,     4,     1,   320],
       [ 1375,     4,   492, ...,   149,   336,   556],
       ..., 
       [   44,    21,   201, ...,    13,   417,  5907],
       [  788, 19456,  4878, ...,     1,  6620,   181],
       [   15,    64,  3913, ...,   957,     4,  2144]], dtype=int32)

In [60]:
padded_sequences_test.shape

(10000, 70)

In [71]:
padded_sequences_test[:100]

array([[   11,     6,    87, ...,    55,    82,    17],
       [10361,   182,   175, ...,     4,     1,   320],
       [ 1375,     4,   492, ...,   149,   336,   556],
       ..., 
       [   11,     6,  1561, ...,     3,  1785,  4416],
       [   38,     2,  4315, ...,    11,   338,   177],
       [ 1825,    19,    96, ...,     3,     5,  1507]], dtype=int32)

In [88]:
padded_sequences_test.shape

(10000, 70)

In [61]:
padded_sequences_test[0]

array([   11,     6,    87,     8,     6,    19,     1,  2116,  5349,
        8931,    15,    44,    30,   953,    72,  9375,    97,    22,
          36,  8644,     3,    23, 12342,  1428,   812,    37,   225,
          26,    81,   129,  2892,    87,     5,   506,   102,    10,
          62,    25,  5862,    14,   159,   706,  1711,    98,    67,
          25,    52,    15,     1,   100,    26,     5,    25,  4387,
           3,    56,    24,   979,    11, 13373,     7,     9,    17,
           5,   285,     8,     2,    55,    82,    17], dtype=int32)

In [16]:
np.array([np.hstack(([0], padded_sequences_test[0][:3], padded_sequences_test[0][4:]))]).shape

(1, 70)

In [17]:
list(generate(padded_sequences_test[:1]))[0].shape

(70,)

In [27]:
index_to_word = {index: word for word, index in tokenizer.word_index.items()}

## Model

In [18]:
# load json and create model
json_file = open(MODEL_NAME + '.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

# load weights into new model
loaded_model.load_weights(MODEL_NAME + ".hdf5")
metrics=['accuracy', 'fmeasure', 'precision', 'recall']
loaded_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=metrics)
print("Loaded '%s' model from disk" % MODEL_NAME)

Loaded 'models/lstm_word2vec' model from disk


In [19]:
loaded_model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
embedding_1 (Embedding)          (None, 70, 300)       6000000     embedding_input_1[0][0]          
____________________________________________________________________________________________________
bidirectional_1 (Bidirectional)  (None, 256)           439296      embedding_1[0][0]                
____________________________________________________________________________________________________
dropout_1 (Dropout)              (None, 256)           0           bidirectional_1[0][0]            
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 1)             257         dropout_1[0][0]                  
Total params: 6,439,553
Trainable params: 439,553
Non-trainable params: 6,000,000
_________

In [20]:
def padding(text):
    return pad_sequences(tokenizer.texts_to_sequences([text]), maxlen=MAX_SEQUENCE_LENGTH)

In [21]:
def lstm_predict(text):
    return loaded_model.predict(padding(preprocess(text)))[0][0]

In [22]:
lstm_predict("not bad")

0.65912336

In [130]:
lstm_predict("good")

0.91656721

In [116]:
def generate(sequence):
    rez = []
    for i in range(len(sequence)):
        rez.append(np.hstack(([0], sequence[:i], sequence[i+1:])))
    return np.array(rez)

In [25]:
def predict(hacked):
    return [p[0] for p in loaded_model.predict(hacked)]

In [93]:
def compare(sequences, seq_preds):
    word_scores = {}
    for si, seq in enumerate(sequences):
        
        hacked = generate(seq) # 70x70
        preds = predict(hacked)
        
        #70x1
        for i, word in enumerate(seq):
            
            seq_score = seq_preds[si]
            
            if word not in word_scores:
                word_scores[word] = []
            
            #word_scores[word].append((seq_score, preds[i], si))
            word_scores[word].append((seq_score - preds[i], si))
    
    return word_scores

In [128]:
def seq_to_words(sequence):
    result = []
    for word_idx in sequence:
        word = index_to_word.get(word_idx, "NA")
        result.append(word)
    return " ".join(result)

In [154]:
def inspect_sample(sample_id):
    sample = padded_sequences_test[sample_id]
    pred = predict(np.array([sample]))[0]
    hacked = generate(sample)
    hacked_preds = predict(hacked)
    result = []
    for i, word_idx in enumerate(sample):
        result.append([index_to_word.get(word_idx, "NA"), pred - hacked_preds[i]])
    return seq_to_words(sample), result

In [132]:
word_scores = compare(padded_sequences_test[:1000], predict(padded_sequences_test[:1000]))

In [136]:
word_values = []
for word_index, scores in word_scores.items():
    s = sorted(scores)
    Min = s[0]
    Max = s[-1]
    word_values.append({
        'word': index_to_word.get(word_index, 'NAN'),
        'min': Min[0],
        'max': Max[0],
        'mean': np.mean(s, axis=0)[0],
        'value': sum([abs(si[0]) for si in s])/len(s),
        'count': len(s),
        'pos_count': len([s0 for s0 in s if s0[0] > 0]),
        'neg_count': len([s0 for s0 in s if s0[0] < 0]),
        'min_sample_id': Min[1],
        'max_sample_id': Max[1],
    })

In [137]:
rez = pd.DataFrame(word_values)

In [138]:
rez.shape

(7651, 10)

In [144]:
rez[rez['word'] == 'bad']

count       max  max_sample_id      mean     min  min_sample_id  \
82  129    0.526629  213           -0.055462 -0.8364  0               

    neg_count  pos_count     value word  
82  102        27         0.067578  bad

In [148]:
rez[rez['value']>0.05][rez['pos_count'] > 3].sort_values(by=['value'], ascending=False)

/dvl/udsclub/.env/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if __name__ == '__main__':


count       max  max_sample_id      mean       min  min_sample_id  \
3391  5      0.456302  213            0.177153 -0.003280  262             
1448  5      0.502542  213            0.115155 -0.112754  383             
510   38     0.321842  526           -0.080531 -0.724063  879             
808   22     0.884046  815            0.131202 -0.016953  692             
981   6      0.225996  789           -0.018612 -0.443536  576             
744   15     0.588446  213           -0.039198 -0.490372  718             
1562  6      0.511646  940            0.088551 -0.086811  623             
1801  4      0.356187  469            0.115665  0.000590  681             
2252  4      0.425031  15             0.113830  0.000140  368             
2930  8      0.286658  965            0.112643 -0.002414  187             
1502  6      0.333772  124            0.016452 -0.232754  161             
651   15     0.283599  411           -0.017662 -0.421425  7               
1540  5      0.196921  475            0.109937  0.005810  616             
881   15     0.685247  850            0.104556 -0.039170  331             
1516  6      0.161149  474            0.098292 -0.021642  305             
919   4      0.246030  247            0.103926  0.000128  358             
1463  10     0.243506  579            0.018131 -0.292348  445             
1060  8      0.273963  15             0.067820 -0.047470  389             
1525  5      0.309497  379            0.094604 -0.020178  436             
1008  9      0.128315  644           -0.022103 -0.389526  7               
665   8      0.055736  251           -0.072914 -0.370964  400             
1000  13     0.503676  213            0.016160 -0.232278  293             
398   14     0.283090  965            0.010003 -0.515444  538             
624   7      0.267981  379           -0.019200 -0.222115  138             
1341  6      0.088846  937           -0.059238 -0.372564  394             
2480  6      0.161716  474            0.059352 -0.103260  776             
6360  6      0.188888  375            0.068856 -0.076690  53              
484   16     0.125573  398           -0.075872 -0.716417  138             
760   19     0.167575  852           -0.052966 -0.452888  576             
655   13     0.653601  213            0.062637 -0.139055  538             
...   ..          ...  ...                 ...       ...  ...             
240   32     0.185651  164           -0.030779 -0.374016  445             
435   37     0.328497  623            0.003839 -0.167609  718             
420   19     0.196664  247           -0.003102 -0.281486  485             
856   7      0.210898  88             0.049108 -0.008672  187             
155   46     0.314479  399           -0.006173 -0.204152  979             
139   57     0.490815  968           -0.004373 -0.345709  177             
1164  9      0.184820  526            0.051377 -0.000347  460             
695   11     0.081274  855           -0.026461 -0.345856  445             
731   7      0.165030  764            0.026864 -0.062607  392             
491   11     0.018354  399           -0.045616 -0.371357  445             
1752  10     0.419957  969            0.048769 -0.005671  335             
676   12     0.235110  15             0.027394 -0.072915  891             
188   32     0.173878  350           -0.019353 -0.264894  400             
571   14     0.018266  38            -0.047222 -0.444180  555             
351   19     0.176864  152           -0.030278 -0.264357  94              
104   88     0.378109  763           -0.019433 -0.414559  7               
236   40     0.465825  213           -0.001782 -0.181122  403             
249   50     0.233801  789           -0.018800 -0.318990  161             
984   9      0.005022  731           -0.049419 -0.168464  538             
182   36     0.228646  72             0.000330 -0.396749  292             
434   9      0.387511  969            0.037649 -0.044752  678             
170   50     0.141084  474     

In [155]:
inspect_sample(776)

("so so episodes of star trek the next generation that thinks it has something important to say you'll see every plot twist a mile off in this by the numbers romp however it's worth seeing for its portrayal of drag king prostitutes a brothel where young women pay old men to have sex with them how's that for role reversal and lesbian soap operas the ghost of valerie lives !",
 [['so', -0.12658682],
  ['so', -0.12658682],
  ['episodes', 0.060997218],
  ['of', -0.15322432],
  ['star', -0.24555662],
  ['trek', 0.081950992],
  ['the', -0.14997968],
  ['next', -0.15827957],
  ['generation', -0.02629602],
  ['that', -0.084673554],
  ['thinks', -0.19380382],
  ['it', -0.055898994],
  ['has', -0.05431062],
  ['something', -0.083150059],
  ['important', -0.010306358],
  ['to', -0.028164923],
  ['say', -0.20885143],
  ["you'll", -0.026362062],
  ['see', -0.044323981],
  ['every', -0.084624797],
  ['plot', -0.12561074],
  ['twist', 0.015751749],
  ['a', -0.047543168],
  ['mile', -0.17559072],
  ['